### ISSUE TITLE
Update to API 8

### ISSUE THREAD

**Issue by Imaginary-Narwhal** [digital-pet/AetherSenseRedux#14]
Any chance of an update to the new API?

**Comment by digital-pet** [comment]
I'll take a look at it soon, I'm currently unsubbed but it should just be a simple update and build.

**Comment by digital-pet** [comment]
The dalamud part is a simple update but it appears that the Buttplug FFI has changed substantially with v3.0.0, it'll take a little bit for me to get this updated.

**Comment by digital-pet** [comment]
Preliminary work is in #15 and it builds and runs but additional work will need to be done before I am comfortable releasing an updated version.
