### ISSUE TITLE
Plugin can't be downloaded

### ISSUE THREAD

**Issue by Mirakai1** [digital-pet/AetherSenseRedux#17]
Is this project dead? I tried to add the custom repo in the dalamud plugin settings but no new plugins were added. It just seems to... not work anymore

**Comment by digital-pet** [comment]
It hasn't been updated for the current version of dalamud due to personal issues preventing me from devoting time to the project at the same time as some substantial API changes occured in upstream libraries. I expect to release the next version alongside the release of Dawntrail.

**Comment by digital-pet** [comment]
See here for future developments on this issue

https://github.com/aka-tamagotchi/AetherSenseRedux/issues/18
